name: lint

on:
  push:
    paths:
      - '.github/workflows/*'

jobs:
  lint-workflow-files:
    name: lint workflow files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - uses: docker://rhysd/actionlint:latest
