name: lint

on:
  push:
    paths:
      - '.github/workflows/*'

jobs:
  lint-workflow-files:
    name: lint workflow files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - uses: docker://rhysd/actionlint:latest
